Repository Motonary/Fortuna, pull requests merged in 2019-02, with the labels that each got.

#82 Create database tests
  .gitignore
  config/.keep
  config/testdatas.yml
  database/database.go
  database/database_test.go
  testdata/init.go
Labels: backend, emergency

#86 Improve reducer structure
  client/src/actions/users.ts
  client/src/components/organisms/Form/index.tsx
  client/src/components/organisms/Form/types.ts
  client/src/constants/action-types.ts
  client/src/constants/static-types.ts
  client/src/reducers/index.ts
  client/src/reducers/reducer-type.ts
  client/src/reducers/users.ts
Labels: emergency, frontend

#96 Arrange folders
  client/src/actions/static-types.ts
  client/src/actions/users.ts
  client/src/constants/index.ts
  client/src/constants/static-types.ts
  client/src/constants/url.ts
  client/src/reducers/static-types.ts
  client/src/reducers/users.ts
Labels: refactoring

#97 Hash passowrd
  client/src/actions/users.ts
  client/src/components/organisms/Form/index.tsx
  client/src/components/organisms/Form/types.ts
  client/src/constants/functions.ts
Labels: enhancement, frontend

#114 Remove jest and enzyme
  .gitignore
  client/package.json
  client/src/__mocks__/fileMock.js
  client/src/__mocks__/fileTransformer.js
  client/src/__tests__/atoms/button.test.tsx
  client/tsconfig.json
  client/yarn.lock
Labels: frontend

#115 Collect client errors and send to api
  client/src/actions/users.ts
  client/src/app.tsx
Labels: frontend

#116 Fix typo
  client/src/actions/users.ts
Labels: bug, frontend
