Repository Motonary/Fortuna, pull requests merged in 2019-01, with the labels that each got.

#22 Install react
  .gitignore
  client/.yarnrc
  client/dist/index.html
  client/package.json
  client/src/__mocks__/.keep
  client/src/__tests__/.keep
  client/src/actions/.keep
  client/src/app.tsx
  client/src/components/Hello.tsx
  client/src/components/atoms/.keep
  client/src/components/molecules/.keep
  client/src/components/organisms/.keep
  client/src/components/pages/.keep
  client/src/components/templates/.keep
  client/src/components/utils/.keep
  client/src/constants/.keep
  client/src/reducers/.keep
  client/tsconfig.json
  client/tslint.json
  client/types/images.d.ts
  client/webpack.config.js
  client/yarn.lock
Labels: enhancement

#23 Construct go directory
  Gopkg.lock
  Gopkg.toml
  api/.keep
  cmd/.keep
  config/.keep
  database/.keep
  deployment/.keep
  init/.keep
  schema/.keep
  vendor/.keep
Labels: backend, emergency

#29 Fix
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
Labels: bug

#28 Install storybook
  client/package.json
  client/src/.storybook/addons.js
  client/src/.storybook/config.js
  client/src/.storybook/webpack.config.js
  client/src/components/atoms/.keep
  client/src/components/atoms/demo/demo.stories.tsx
  client/src/components/atoms/demo/demo.tsx
  client/src/components/atoms/demo/style.scss
  client/yarn.lock
Labels: enhancement, frontend

#32 Improve husky in package.json
  client/package.json
  client/src/components/atoms/demo/demo.tsx
Labels: refactoring

#35 Install mini-css-extract-plugin
  client/package.json
  client/webpack.config.js
  client/yarn.lock
Labels: emergency, frontend

#30 API for user
  api/.keep
  api/handler/user_handler.go
  api/handler/user_handler_test.go
  api/router/router.go
  api/router/router_test.go
  cmd/.keep
  cmd/main.go
  entity/user.go
Labels: backend

#37 Modify circleci config
  .circleci/config.yml
  cmd/main.go
Labels: backend, enhancement

#40 Create DB
  database/.keep
  database/database.go
  entity/user.go
Labels: backend, emergency, enhancement

#43 Merge for fix circle ci err
  .circleci/config.yml
  api/router/router.go
  api/router/router_test.go
  entity/user.go
Labels: bug

#42 subtle change
  .gitignore
  database/database.go
  entity/user.go
Labels: enhancement

#36 Struct Form components
  .gitignore
  client/package.json
  client/src/__mocks__/.keep
  client/src/__mocks__/fileMock.js
  client/src/__mocks__/fileTransformer.js
  client/src/__tests__/.keep
  client/src/__tests__/atoms/button.test.tsx
  client/src/app.tsx
  client/src/components/Hello.tsx
  client/src/components/atoms/Button/index.stories.tsx
  client/src/components/atoms/Button/index.tsx
  client/src/components/atoms/Button/style.css
  client/src/components/atoms/Button/style.css.d.ts
  client/src/components/atoms/TextBox/index.tsx
  client/src/components/atoms/TextBox/style.css
  client/src/components/atoms/TextBox/style.css.d.ts
  client/src/components/atoms/demo/demo.stories.tsx
  client/src/components/atoms/demo/demo.tsx
  client/src/components/atoms/demo/style.scss
  client/src/components/organisms/.keep
  client/src/components/organisms/Form/form-types.ts
  client/src/components/organisms/Form/index.stories.tsx
  client/src/components/organisms/Form/index.tsx
  client/src/components/organisms/Form/style.css
  client/src/components/organisms/Form/style.css.d.ts
  client/src/components/pages/.keep
  client/src/components/pages/TopPage/index.tsx
  client/src/components/properties.css
  client/src/components/templates/.keep
  client/src/components/templates/TopPageTemplate/index.stories.tsx
  client/src/components/templates/TopPageTemplate/index.tsx
  client/src/components/utils/auth.tsx
  client/src/reducers/index.ts
  client/tsconfig.json
  client/webpack.config.js
  client/yarn.lock
Labels: frontend

#47 tsconfig.jsonの最適化
  client/tsconfig.json
Labels: enhancement, frontend

#38 create action and reducer for user
  client/package.json
  client/src/.storybook/config.js
  client/src/actions/.keep
  client/src/actions/users.ts
  client/src/app.tsx
  client/src/components/atoms/Button/style.css
  client/src/components/organisms/Form/form-types.ts
  client/src/components/organisms/Form/index.stories.tsx
  client/src/components/organisms/Form/index.tsx
  client/src/components/organisms/Form/types.ts
  client/src/components/templates/TopPageTemplate/index.tsx
  client/src/constants/.keep
  client/src/constants/action-types.ts
  client/src/constants/static-types.ts
  client/src/constants/url.ts
  client/src/reducers/index.ts
  client/src/reducers/users.ts
  client/yarn.lock
Labels: frontend
